apiVersion: v1
kind: Pod
metadata:
    name: busybox-shell
    labels:
        name: busybox-shell
spec:
    restartPolicy: Never
    containers:
      - resources:
          limits:
             cpu: 0.5
        image: gcr.io/google_containers/busybox
        name: busybox1
        command:
         - "/bin/sh"
         - "-c"
         - "while true; do sleep 1; done"
        volumeMounts:
          - name: vol
            mountPath: /mnt/test
    volumes:
      - name: vol
        persistentVolumeClaim:
            claimName: snapshot-data-claim

