apiVersion: v1
kind: Pod 
metadata:
    name: file-copy
    labels:
        name: file-copy 
spec:
    restartPolicy: Never
    containers:
    - resources:
        limits:
          cpu: 0.5
      image: gcr.io/google_containers/busybox
      command:
         - "/bin/sh"
         - "-c"
         - "while true; do date >> /mnt/test/pod-out.txt; sleep 10; done"
      name: busybox
      volumeMounts:
      - name: vol
        mountPath: /mnt/test
    volumes:
        - name: vol
          hostPath:
              path: /tmp/test 
