apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: snapshot-data-claim
    namespace: default
    annotations:
        snapshot.alpha.kubernetes.io/snapshot: snapshot-demo
spec:
    accessModes: ["ReadWriteOnce"]
    resources:
        requests:
            storage: 1Gi
    storageClassName: snapshot-promoter
