kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: myclaim1
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: slow
    resources:
        requests:
            storage: 2000Mi
