apiVersion: v1
kind: Pod
metadata:
  name: share-volume-1
spec:
  containers:
    - name: container-1 
      image: gcr.io/google_containers/busybox:1.24
      command: ["sh", "-c"]
      args:
        - sleep 10;
          while true; do
            echo "this is container1" >> /etc/test.txt;
            sleep 5;
          done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: test-vol
          mountPath: /etc
    - name: container-2
      image: gcr.io/google_containers/busybox
      command: 
        - "sh"
        - "-c"
        - "while true; do if [[ ! -f /etc/test.txt ]]; then touch /etc/test.txt;fi; if [[ -e /etc/test.txt ]]; then date >> /etc/test.txt;fi; sleep 1; done;"
      resources:
        limits:
          cpu: 0.5
      volumeMounts:
        - name: test-vol
          mountPath: /etc
  volumes:
    - name: test-vol 
      hostPath:
        path: /tmp/testvol
